# Generated by Django 3.2.4 on 2021-06-19 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_album_musician'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='full_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='shirt_sizes',
            field=models.CharField(choices=[('L', 'Large'), ('M', 'Medium'), ('S', 'Small')], max_length=1, null=True),
        ),
    ]
