# Generated by Django 3.2.4 on 2021-06-19 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_runner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.musician', verbose_name='Artist Name'),
        ),
        migrations.AlterField(
            model_name='album',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Album Name '),
        ),
        migrations.AlterField(
            model_name='album',
            name='number_stars',
            field=models.IntegerField(default=0, verbose_name='stars '),
        ),
        migrations.AlterField(
            model_name='musician',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='First name '),
        ),
        migrations.AlterField(
            model_name='musician',
            name='instruments',
            field=models.CharField(max_length=30, verbose_name='Instrument'),
        ),
        migrations.AlterField(
            model_name='musician',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='full_name',
            field=models.CharField(max_length=30, null=True, verbose_name='Full Name '),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='Last Name '),
        ),
        migrations.AlterField(
            model_name='runner',
            name='medal',
            field=models.CharField(blank=True, choices=[('GOLD', 'Gold'), ('SILVER', 'Silver'), ('BRONZE', 'Bronze')], max_length=20, verbose_name='The Medal '),
        ),
        migrations.AlterField(
            model_name='runner',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Runner Name '),
        ),
    ]
