# Generated by Django 3.2.4 on 2021-06-20 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0009_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelTable(
            name='student',
            table='Student_info',
        ),
    ]
